 version: '2'

 services:

    nginx:
        build:
            context: .
            dockerfile: .docker/nginx.dev.dockerfile
        container_name: commercefacile-ngnix
        volumes:
            - ./:/var/www/
        links:
            - commercefacile-server
        ports:
            - "80:80"
            - "443:443"
        networks:
            - commercefacileapp-network

    commercefacile-queue:
        image: thomasdolar/beanstalkd
        container_name: commercefacile-queue
        ports:
            - "11300:11300"
            - "8080:8080"
        networks:
            - commercefacileapp-network

    commercefacile-server:
        build:
            context: .
            dockerfile: .docker/server.dockerfile
        container_name: commercefacile-server
        privileged: true
        volumes:
            - ./:/var/www/
            - /var/lib/redis
        depends_on:
            - commercefacile-db
        links:
            - commercefacile-db
        networks:
            - commercefacileapp-network

    commercefacile-db:
        image: postgres:latest
        container_name: commercefacile-db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=commercefacile
            - POSTGRES_USER=commercefacile
            - POSTGRES_PASSWORD=commercefacile
        networks:
            - commercefacileapp-network

    commercefacile-redis:
        image: sameersbn/redis
        container_name: commercefacile-redis
        volumes_from:
            - commercefacile-server
        ports:
            - "6379:6379"
        networks:
            - commercefacileapp-network

    commercefacile-socket:
        build:
            context: .socket
        container_name: commercefacile-socket
        links:
            - commercefacile-redis:redis
        depends_on:
            - commercefacile-redis
        ports:
            - "8443:8443"
        networks:
            - commercefacileapp-network

 networks:
    commercefacileapp-network:
        driver: bridge
